services:
  k3s:
    image: rancher/k3s:latest
    command: server --disable=traefik
    privileged: true
    ports:
      - "6443:6443"   # kubectl API
      - "8082:80"     # ingress HTTP
      - "30080:30080" # laravel nodeport
    volumes:
      - k3s_server:/var/lib/rancher/k3s
    environment:
      - K3S_TOKEN=devops-secret-token
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    networks: [app_network, k8s]

  portainer:
    image: portainer/portainer-ce:latest
    ports: ["9000:9000"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks: [k8s]

networks:
  app_network:
    external: true
  k8s:
    name: k8s_network

volumes:
  k3s_server:
  portainer_data: