apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel
type: Opaque
stringData:
  DB_USERNAME: root
  DB_PASSWORD: secret
  APP_KEY: base64:jwNkt8RiMWGdTmwJkhRAf+jE4OUOk27LWS/AwHLNOXg=
